### ISSUE TITLE
CI for repo

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/pyFlowSOM#1]
**Is your feature request related to a problem? Please describe.**
@y2kbugger, did you decide on if you want to use Github actions or Travis CI? If the former, let me know if you need any admin approvals. If the latter, @alex-l-kong can set up the basics.

**Comment by y2kbugger** [comment]
I think i'll try Travis first, since you already have some set up that way.
I've never used travis though.

**Comment by ngreenwald** [comment]
Got it, sounds good. If it ends up causing lots of headache, feel free to reach out to Alex for help, or switch to GA.

**Comment by y2kbugger** [comment]
https://pypi.org/project/cibuildwheel/

[Documentation](https://cibuildwheel.readthedocs.org/)

Python wheels are great. Building them across Mac, Linux, Windows, on multiple versions of Python, is not.

cibuildwheel is here to help. cibuildwheel runs on your CI server - currently it supports GitHub Actions, Azure Pipelines, Travis CI, AppVeyor, CircleCI, and GitLab CI - and it builds and tests your wheels across all of your platforms.

**Comment by y2kbugger** [comment]
Another tool for cross platform binary builds https://scikit-build.readthedocs.io/en/latest/
