### ISSUE TITLE
Cross platform builds

### ISSUE THREAD

**Issue by y2kbugger** [angelolab/pyFlowSOM#4]
Need a way to build wheels for all platforms

**Comment by y2kbugger** [comment]
https://pypi.org/project/cibuildwheel/

[Documentation](https://cibuildwheel.readthedocs.org/)
[Working examples](https://cibuildwheel.readthedocs.io/en/latest/working-examples/)

> Python wheels are great. Building them across Mac, Linux, Windows, on multiple versions of Python, is not.
> 
> cibuildwheel is here to help. cibuildwheel runs on your CI server - currently it supports GitHub Actions, Azure Pipelines, Travis CI, AppVeyor, CircleCI, and GitLab CI - and it builds and tests your wheels across all of your platforms.

**Comment by y2kbugger** [comment]
Another possible tool for cross platform binary builds https://scikit-build.readthedocs.io/en/latest/

**Comment by ngreenwald** [comment]
I was just about to suggest spying on whatever scikit does, given that so much of their stuff is written in C under the hood. Makes sense that they'd have their own tool, didn't even think about that.
