### ISSUE TITLE
Change c code to be able to handle large datasets

### ISSUE THREAD

**Issue by cliu72** [angelolab/pyFlowSOM#6]
**Is your feature request related to a problem? Please describe.**
If you remember way back when (I showed this in computational subgroup meeting like almost a year ago), I showed the decidua dataset where I increased the number of total iterations (number of pixels x number of passes) to almost 10 billion, and it was resulting in terrible results. The reason was because in the c code, `niter` (which is the number of passes x the number of pixels) is declared as an int, which has a max value of 2^31.

This is the slide I shared:
![image](https://user-images.githubusercontent.com/11382352/208762758-eb9c6f9d-2ad6-40b1-8d85-1f4a244ceb2b.png)

For very large datasets, this causes problems.

**Describe the solution you'd like**
In `flowsom.c`, change `niter` (which is the total number of iterations) to be double, and change `k`, which is the counter for the iterations, to be a double as well. I already tested this change in the FlowSOM package, and it worked well, so I don't anticipate it being an issue here. However, this does require rebuilding the package (I think).

Code should look like this at the beginning of C_SOM (https://github.com/angelolab/pyFlowSOM/blob/c7989bdaaaa2f3d23c936df4c0b64c2769198353/pyFlowSOM/flowsom.c#L72-L90):

```
void C_SOM(
    double *data,
    double *nodes,
    double *nhbrdist,
    double alpha_start,
    double alpha_end,
    double radius_start,
    double radius_end,
    double *xdists, /* working arrays */
    int n,
    int px,
    int n_nodes,
    int rlen,
    int dist
    )
{
    int cd, i, j, nearest;
    double k, niter;
    double tmp, threshold, alpha, thresholdStep;
    double change;
```

**Comment by cliu72** [comment]
@ngreenwald

**Comment by ngreenwald** [comment]
Sounds good, we'll address this before making a new release

**Comment by y2kbugger** [comment]
Just in case anyone didn't catch it: updating the package is in the readme:
![image](https://user-images.githubusercontent.com/6101677/208955968-cfcfa91d-4346-4949-ada4-7e04f397ba4b.png)

Just tag the commit with the new version and push.

To run tests without publishing, just push the commit without tagging it.

**Comment by ngreenwald** [comment]
Awesome, thanks Zak!
